### PR TITLE
Remove cbrooks from the admin group

### PR DESCRIPTION
**Pull request by KellerFuchs**
Their access is incomplete anyhow (not in the keyring for signing repos, for pass DB, no IRC oper password, ...), and they seems to be gone.

@connerbrooks If you want to stay in the admin group, please close this PR and send one that adds your missing access instead.

### CODE REVIEW

**Comment by drGrove** [comment]
I'll work with cbrooks to get his life together today.

**Comment by KellerFuchs** [comment]
@drGrove Is that still happening?

**Comment by drGrove** [comment]
Yes, I didn't get a chance over the weekend to work with him. I'll make
time this weekend

**Review by lrvick — APPROVED** [review]

**Comment by drGrove** [comment]
I'll make sure to work with @connerbrooks to get this resolved. I also need to update my stuff due to the yubikey fiasco on my side. Which will probably mean i'll have a new key and access to setup as well. Otherwise let's submit this on Monday 5/8 PST

**Comment by KellerFuchs** [comment]
Merged and deployed.

@connerbrooks Happy to have you back once you have time to spare  :)

**Pull request merged**
