### PR TITLE
Reissue the hashbang.sh certificate

### PR DESCRIPTION
**Pull request by KellerFuchs**
I just got GlobalSign to reissue our certificate, as the vault was potentially compromised by ROCA.
OK for deploying this and revoking the previous cert?

### CODE REVIEW

**Review by RyanSquared — APPROVED** [review]

**Comment by KellerFuchs** [comment]
Deployment in progress

**Comment by KellerFuchs** [comment]
Revokation of the old certificate requested.

**Comment by KellerFuchs** [comment]
Confirmed revoked in the <http://ocsp2.globalsign.com/gsdomainvalsha2g2> CRL

**Comment by KellerFuchs** [comment]
New (pre)certificate [observed](https://crt.sh/?id=258736530) in Certificate Transparency logs.

**Pull request merged**
