### PR TITLE
irc: Even more SPAM filters yet again

### PR DESCRIPTION
**Pull request by KellerFuchs**

### CODE REVIEW

**Review by DeviaVir — DISMISSED** [review]
this SPAM is insane

**Review by DeviaVir — APPROVED** [review]
:+1: that banner though

**Comment by KellerFuchs** [comment]
@DeviaVir Had a pretty stressful 30s with “wait, what's the passphrase for my #! OpenPGP key” :sob: 
Thanks a bunch for the review.

**Comment by DeviaVir** [comment]
@KellerFuchs haha, been there. Np!

**Pull request merged**
