### PR TITLE
Manage LDAP passwords with Ansible

### PR DESCRIPTION
**Pull request by KellerFuchs**
This is needed to change provisor's password.
Unfortunately, I have 0 confidence it won't break all the things.

Also, it requires Ansible 2.3+ and `python-ldap`.

### CODE REVIEW

**Comment by KellerFuchs** [comment]
@hashbang/contributers No daring, dashing, brave reviewer?
https://www.youtube.com/watch?v=bWcASV2sey0

**Comment by KellerFuchs** [comment]
Though https://www.youtube.com/watch?v=hCjkuCJrxq0 is a much more awesome version of it.

**Comment by KellerFuchs** [comment]
@hashbang/administrators If no review is going to be forthcoming, just let me know and I will run it, watch the fireworks, and put out the fires...

**Review by DeviaVir — DISMISSED** [review]
LGTM, let's see some fireworks

**Comment by KellerFuchs** [comment]
@DeviaVir OK, let's blow things up  :boom:

**Comment by KellerFuchs** [comment]
@DeviaVir Deployed with no change, let's see what I borked.

**Comment by KellerFuchs** [comment]
Things work again, but I had to change the provisor password by hand...

**Comment by KellerFuchs** [comment]
@DeviaVir As far as I can tell, my `ldap_passwd` module is complete, and works in the playbook in “check mode”.  OK for trying a new provisor password change, hopefully with less fireworks?

**Comment by KellerFuchs** [comment]
@DeviaVir Set a new provisor password and ran it; worked like a charm.  <3
Can you review, so we can merge?

**Review by DeviaVir — APPROVED** [review]

**Pull request merged**
