### PR TITLE
Add echelon as an IRC operator

### PR DESCRIPTION
**Pull request by KellerFuchs**
@jxechelon Generate a client certificate and send us the fingerprint; it's [documented](https://github.com/hashbang/admin-tools/blob/master/doc/New_admin.md#certificate-authentication)

@hashbang/administrators I suggest we vote on this directly on the issue (with :+1: and :-1: reactji) and tally the total in a week (or less if we get 5 votes or more, since that's a majority).

### CODE REVIEW

**Review by DeviaVir — DISMISSED** [review]

**Comment by KellerFuchs** [comment]
@DeviaVir You can review now  ;)

**Review by DeviaVir — APPROVED** [review]
:+1:

**Comment by singlerider** [comment]
:+1:

**Comment by KellerFuchs** [comment]
Deployed.

**Pull request merged**
