### PR TITLE
Add board members email alias

### PR DESCRIPTION
**Pull request by drGrove**

### CODE REVIEW

**Review by KellerFuchs — CHANGES_REQUESTED** [review]
I think the group `board_members` ought to be renamed to `board`.
Other than that, LGTM now.

**Comment by KellerFuchs** [comment]
@drGrove As I said on IRC, I didn't merge this (as I had feedback left) but I think you accidentally pushed the first commit of the branch (8e2f92ea95d8d6929f71d001e2fbf541322ea7ea) to `master`.

I reverted that, rebased your entire branch (and squashed the first 2 commits together) so it wouldn't conflict with the revert, and activated branch protection on `master` so we can't accidentally push to it without PR anymore.

**Comment by drGrove** [comment]
Thanks @KellerFuchs, sorry about that

**Comment by KellerFuchs** [comment]
No problem :3

**Comment by drGrove** [comment]
@KellerFuchs ready for review

**Comment by RyanSquared** [comment]
It looks like this is a partial PR and that some earlier commits may have been pushed to master, based on the GitHub web UI's changelist.

**Comment by drGrove** [comment]
@RyanSquared this should be resolved now. Thanks for noticing!

**Comment by drGrove** [comment]
Ping @KellerFuchs @RyanSquared @lrvick

**Review by RyanSquared — APPROVED** [review]

**Review by lrvick — APPROVED** [review]

**Review by DeviaVir — APPROVED** [review]

**Comment by drGrove** [comment]
@lrvick @DeviaVir @KellerFuchs can one of you merge this please?

**Comment by drGrove** [comment]
Actually @KellerFuchs I need you to approve this as well

**Review by KellerFuchs — APPROVED** [review]

**Comment by KellerFuchs** [comment]
@drGrove FWIW, you can dismiss someone's review if you handled their change request.

However, I took the opportunity to flatten the branch's history, as it was needlessly messy.

**Comment by KellerFuchs** [comment]
Lint failure is unrelated, you can go ahead and merge.

**Pull request merged**
