### PR TITLE
hosts: Deprovisioning lon1.irc

### PR DESCRIPTION
**Pull request by KellerFuchs**
Cf thread on team@

### CODE REVIEW

**Comment by KellerFuchs** [comment]
_pokes @RyanSquared with a sharp stick._

**Review by singlerider — APPROVED** [review]
I don't fully understand the implications of deprovisioning this server, but the changes look good to me.

**Review by RyanSquared — APPROVED** [review]
Honestly, thought I reviewed this already. Approving.

**Comment by KellerFuchs** [comment]
@singlerider Well, it was borked, so I destroyed the VM, but the Ansible inventory needed to be updated.

**Pull request merged**
