### PR TITLE
Improve credentials handling

### PR DESCRIPTION
**Pull request by KellerFuchs**
- [x] Simplify the `authorized_key` logic in `sync.yml`.
- [x] Apply the same simplification in `coreos-authorized_keys.d`.
- [x] Automatically remove pubkeys not in Ansible (on the CoreOS boxes).
- [x] Split the credential handling in a separate playbook.
- [x] Document the role of the various playbooks.

### CODE REVIEW

**Comment by KellerFuchs** [comment]
Ok for merge?

**Comment by KellerFuchs** [comment]
~~The missing point depends on https://github.com/hashbang/ansible-authorized_keys.d/pull/2 being reviewed.~~

**Comment by KellerFuchs** [comment]
@hashbang/administrators This is review-ready and tested.

**Comment by KellerFuchs** [comment]
@hashbang/administrators Ping?

**Comment by KellerFuchs** [comment]
@hashbang/administrators Ping?
It would be quite nice to review & merge, given the work being put in https://github.com/hashbang/hashbang/issues/8

**Comment by daurnimator** [comment]
sure I guess. I don't see any reason why not.

**Pull request merged**
