### PR TITLE
added muh name

### PR DESCRIPTION
**Pull request by picardrulez**
gscott

### CODE REVIEW

**Comment by KellerFuchs** [comment]
You are missing a tiny, but important, bit: https://github.com/hashbang/admin-tools/blob/master/group_vars/all#L7-L8

**Comment by picardrulez** [comment]
Do you want the content of the key included in the "All" file or do you want it elsewhere?

**Comment by KellerFuchs** [comment]
@picardrulez Either inline or in `files/keys/gscott.pub`; having large keys directly inline would be annoying, though.
You can also do it like @drGrove and tell Ansible to get the keys from Github (beware, those get put down for root access, so you really have to be sure you want all your GH keys to have that).

**Comment by picardrulez** [comment]
added

**Comment by KellerFuchs** [comment]
@picardrulez Yay, thanks  <3

**Pull request merged**
