### PR TITLE
ldap_ban: Properly quote strings

### PR DESCRIPTION
**Pull request by KellerFuchs**
`ldap_ban.yml` otherwise fails.

### CODE REVIEW

**Comment by daurnimator** [comment]
Use jinja/ansible shell quoting: `{{ string_value | quote }}`

See http://ansible-docs.readthedocs.io/zh/stable-2.0/rst/playbooks_filters.html#other-useful-filters

**Comment by KellerFuchs** [comment]
@daurnimator Thanks, and done (I also switched from `shell` to `command`)

**Comment by daurnimator** [comment]
Looks reasonable, but I don't have facilities to test right now.

**Comment by KellerFuchs** [comment]
@daurnimator FWIW, I just tested (on an already-banned account) and it ran the right command.

**Comment by KellerFuchs** [comment]
@hashbang/administrators Someone else to test/review?

**Review by daurnimator — APPROVED** [review]
If you say it works then I believe it :)

**Review by DeviaVir — APPROVED** [review]

**Comment by KellerFuchs** [comment]
@daurnimator @DeviaVir  Thanks  :)

**Pull request merged**
