### PR TITLE
users: Update aagat's oper pass

### PR DESCRIPTION
**Pull request by KellerFuchs**

### CODE REVIEW

**Review by DeviaVir — APPROVED** [review]

**Comment by KellerFuchs** [comment]
@DeviaVir @RyanSquared While you two are on a roll  :)

**Comment by KellerFuchs** [comment]
Wow, @DeviaVir, that was *fast*  :O

**Comment by DeviaVir** [comment]
@KellerFuchs I was going through notifications while waiting for stuff to build and `dd` to do things... Finally back up to speed. :+1:

**Comment by Aagat** [comment]
Thanks everyone :-)

**Comment by KellerFuchs** [comment]
@DeviaVir I was more mindblown that you had the time to pull the PR locally, check the diff (with decryption) and reply before I even commente don the PR.

**Comment by DeviaVir** [comment]
@KellerFuchs I cheat by grabbing the changed file via github, pulling PR's locally takes too long for single file changes 😒

**Pull request merged**
