### PR TITLE
Update drGroves' OpenPGP Keys

### PR DESCRIPTION
**Pull request by drGrove**

### CODE REVIEW

**Review by DeviaVir — DISMISSED** [review]

**Comment by DeviaVir** [comment]
@drGrove do note that your commit is unverified until you update the public GPG in github.

**Comment by drGrove** [comment]
It's because the email i'm using doesn't match my key. I need to add my other identities. I did this on my work computer and forgot to change the committer email -_-

**Comment by drGrove** [comment]
@DeviaVir @KellerFuchs commit signature is now verified

**Review by KellerFuchs — COMMENTED** [review]
Same as https://github.com/hashbang/password-store/pull/7#pullrequestreview-73706153, you don't need to list the encryption subkey explicitely unless you have a particular reason to.

**Comment by KellerFuchs** [comment]
@drGrove Like for https://github.com/hashbang/password-store/pull/7, I pushed the changes I mentionned. Feel free to send a new PR if that's now what you need/want.

**Review by KellerFuchs — APPROVED** [review]

**Review by DeviaVir — APPROVED** [review]

**Comment by KellerFuchs** [comment]
Aaaah, my push was rejected for some silly reason :sob:

**Pull request merged**
