### PR TITLE
Support `--check` in credentials.yml

### PR DESCRIPTION
**Pull request by KellerFuchs**
- [x] Supports doing dry-runs of this playbook (once hashbang/ansible-authorized_keys.d#8 is merged)
- [x] Much simpler logic for updating `authorized_keys`
- [x] Properly reports the “changed” status (previously, `authorized_keys` was systematically considered to have changed, on shell servers)

The only caveat is that this drops support for fetching SSH keys over HTTPS.
Since @DeviaVir and @drGrove are the only two to use this (and in @DeviaVir's case, I don't know whether it was intentional since there was a `deviavir.pub` with the same key), I flagged them as reviewers.

### CODE REVIEW

**Review by singlerider — COMMENTED** [review]
I am not declining this PR, but I think it's important to mention that in the future, using a GitHub ...`.keys` entry would be valuable. I had to open a PR just to add my outdated public key here that was already updated on GitHub. Had I known it was possible to do so, I'd have done the same as deviavir and dgrove.

**Comment by KellerFuchs** [comment]
@singlerider For what it's worth, you would have had needed to get another admin to run `credentials.yml` anyhow: loading the keys from Github doesn't mean they are automagically pushed to the servers when they change on Github.

**Comment by singlerider** [comment]
@kellerfuchs no, but it's one less place I would have needed to update a file.

**Comment by RyanSquared** [comment]
I think the bigger issue is that it's actually not documented in New_admin.md to add in an SSH key - in either place. Perhaps that should be fixed instead to point to either the files or instructions for the .keys setup.

**Comment by singlerider** [comment]
I will concede to @ryansquared 's point

**Comment by KellerFuchs** [comment]
@singlerider I would argue that having credentials change “magically” without having any file changing is not a feature, but I hope we can agree to keep that discussion out of this PR.

**Review by RyanSquared — APPROVED** [review]
LGTM. Manually tested and all keys are set as they should be. Merging this commit is nondestructive as rerunning the playbook on my system showed no changed deployed keys in it's current state.

**Pull request merged**
